---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sd-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Gi
  hostPath:
    path: /sd-data
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sd-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ''
  volumeMode: Filesystem
  volumeName: pv-sd-data
---
apiVersion: v1
kind: Service
metadata:
  name: sd
  namespace: default
spec:
  ports:
    - name: automatic1111
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: comfy
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-stablediffusion
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: sd
  namespace: default
spec:
  rules:
    - host: automatic1111.sienarfleet.systems
      http:
        paths:
          - backend:
              service:
                name: sd
                port:
                  number: 8080
            path: /
            pathType: Prefix
    - host: comfy.sienarfleet.systems
      http:
        paths:
          - backend:
              service:
                name: sd
                port:
                  number: 8081
            path: /
            pathType: Prefix
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stablediffusion
  annotations: {}
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-stablediffusion
  namespace: default
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-stablediffusion
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-stablediffusion
      namespace: default
    spec:
      runtimeClassName: nvidia
      containers:
        - name: comfyui
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          image: harbor.sienarfleet.systems/stablediffusion/comfy:latest
          args:
            - python 
            - -u 
            - main.py
            - --listen 
            - --port
            - "8081"
          volumeMounts:
            - name: sd-data
              mountPath: /data
        - name: automatic1111
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          # resources:
          #   limits:
          #     nvidia.com/gpu: 1
          image: harbor.sienarfleet.systems/stablediffusion/automatic1111:latest
          args:
            - python 
            - -u 
            - webui.py
            - --listen 
            - --allow-code 
            - --medvram 
            - --xformers 
            - --enable-insecure-extension-access 
            - --api 
            - --port 
            - "8080"
          volumeMounts:
            - name: sd-data
              mountPath: /data
            - name: sd-output
              mountPath: /output
      imagePullSecrets: []
      initContainers:
        - imagePullPolicy: IfNotPresent
          name: models
          image: harbor.sienarfleet.systems/stablediffusion/download:latest
          command:
            - /docker/init.sh
          args:
            - /data
          volumeMounts:
            - name: sd-data
              mountPath: /data
            - name: sd-output
              mountPath: /output
      restartPolicy: Always
      volumes:
        - persistentVolumeClaim:
            claimName: pvc-sd-data
          name: sd-data
  replicas: 1
---