server:
  affinity: ""
  ha:
    enabled: false
  image:
    pullPolicy: IfNotPresent
    repository: harbor.sienarfleet.systems/hashicorp/vault
    tag: 1.11.3
ui:
  enabled: true
  serviceType: ClusterIP
  externalPort: 8200

csi:
  image:
    pullPolicy: IfNotPresent
    repository: harbor.sienarfleet.systems/hashicorp/vault-csi-provider
    tag: 1.2.0

injector:
  agentImage:
    repository: harbor.sienarfleet.systems/hashicorp/vault
    tag: 1.11.3
  image:
    pullPolicy: IfNotPresent
    repository: harbor.sienarfleet.systems/hashicorp/vault-k8s
    tag: 1.0.0
  
