cloudprovider: harvester
cloudCredentialSecretName: cattle-global-data:deathstar
cloudProviderConfigSecretName: secret://fleet-default:services-shared-cloudprovider
cluster:
  annotations: {}
  labels:
    environment: services
    cluster_name: shared
    location: deathstar
  name: services-shared
kubernetesVersion: v1.24.9+rke2r2
monitoring:
  enabled: false
registries:
  configs:
    rgcrprod.azurecr.us:
      authConfigSecretName: carbide-registry
      caBundle: ''
      insecureSkipVerify: false
  mirrors:
    docker.io:
      endpoint:
        - harbor.sienarfleet.systems
rke:
  localClusterAuthEndpoint:
    enabled: false
profile: cis-1.6
selinux: true
secrets_encryption: true
protect_kernel_defaults: true
write_kubeconfig_mode: "0640"
use_service_account_credentials: true
kube_apiserver_arg: 
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- authorization-mode=RBAC,Node
- anonymous-auth=false
- audit-policy-file=/etc/rancher/rke2/audit-policy.yaml
- audit-log-mode=blocking-strict
- audit-log-maxage=30
kube_scheduler_arg:
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kube_controller_manager_arg:
- bind-address=127.0.0.1
- use-service-account-credentials=true
- tls-min-version=VersionTLS12
- tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
kubelet_arg:
- protect-kernel-defaults=true
- read-only-port=0
- authorization-mode=Webhook
- streaming-connection-idle-timeout=5m
nodepools:
- etcd: true
  controlplane: true
  worker: false
  # displayName: control-plane-nodes
  name: control-plane-svc-pool
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  diskSize: 20
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/services
  networkType: dhcp
  imageName: default/ubuntu-rke2-airgap-harvester
  vmNamespace: default
  sshUser: ubuntu
  userdata: |
    bootcmd:
    - systemctl restart systemd-sysctl
    write_files:
    - path: /etc/sysctl.d/60-rke2-cis.conf
      owner: root
      content: |
        vm.panic_on_oom=0
        vm.overcommit_memory=1
        kernel.panic=10
        kernel.panic_on_oops=1
    runcmd:
    - useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U
- etcd: false
  controlplane: false
  worker: true
  # displayName: worker-nodes
  name: worker-svc-pool
  labels: {}
  taints: {}
  quantity: 3
  paused: false
  diskSize: 40
  diskBus: virtio
  cpuCount: 4
  memorySize: 8
  networkName: default/services
  networkType: dhcp
  imageName: default/ubuntu-rke2-airgap-harvester
  vmNamespace: default
  sshUser: ubuntu
  userdata: |
    bootcmd:
    - systemctl restart systemd-sysctl
    write_files:
    - path: /etc/sysctl.d/60-rke2-cis.conf
      owner: root
      content: |
        vm.panic_on_oom=0
        vm.overcommit_memory=1
        kernel.panic=10
        kernel.panic_on_oops=1