apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: osint-webcheck
    {{- if .Values.deployment.labels }}
{{ toYaml .Values.deployment.labels | indent 4 }}
    {{- end }}
  name: osint
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: osint-webcheck
  template:
    metadata:
      labels:
        app: osint-webcheck
        {{- if .Values.deployment.labels }}
{{ toYaml .Values.deployment.labels | indent 8 }}
        {{- end }}
      namespace: {{ .Values.namespace }}
    spec:
      containers:
        - name: osint-webcheck
          env:
            - name: GOOGLE_CLOUD_API_KEY
              value: {{ .Values.api_keys.google_api_key }}
            - name: REACT_APP_SHODAN_API_KEY
              value: {{ .Values.api_keys.shodan_api_key }}
            - name: REACT_APP_WHO_API_KEY
              value: {{ .Values.api_keys.who_api_key }}
            - name: SECURITY_TRAILS_API_KEY
              value: {{ .Values.api_keys.security_trails_api_key }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: {{ .Values.deployment.image_pull_policy }}
          ports:
            - containerPort: 3000
              name: osint
              protocol: TCP
          resources: {}
          securityContext: 
{{ toYaml .Values.deployment.security_context | indent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
