apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: osint
  namespace: default
spec:
  rules:
    - host: osint.awsprod.sienarfleet.systems
      http:
        paths:
          - backend:
              service:
                name: osint
                port:
                  number: 8080
            path: /
            pathType: Prefix
