{{- if eq .Values.ingress.enabled true }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: osint
  namespace: default
  labels:
    app: osint-webcheck
    {{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.url }}
      http:
        paths:
          - backend:
              service:
                name: osint
                port:
                  number: {{ .Values.service.port }}
            path: /
            pathType: Prefix
{{- end }}
