apiVersion: v1
kind: Service
metadata:
  name: osint
  namespace: default
spec:
  ports:
    - name: webcheck
      port: 8080
      protocol: TCP
      targetPort: 3000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-default-osint
  type: ClusterIP
