apiVersion: v1
kind: Service
metadata:
  name: osint
  namespace: {{ .Values.namespace }}
  labels:
    app: osint-webcheck
    {{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
    {{- end }}
spec:
  ports:
    - name: webcheck
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 3000
  selector:
    app: osint-webcheck
  type: {{ .Values.service.type }}
