cloudprovider: amazonec2
cloudCredentialSecretName: cattle-global-data:cc-qb7r4 # aws-multicloud
cluster:
  annotations: {}
  labels:
    gpu: nvidia
    environment: hiperf
    cluster_name: tyreek
    location: aws
  name: rke2-aws-hiperf-tyreek
kubernetesVersion: v1.24.9+rke2r2
system_default_registry: rgcrprod.azurecr.us
monitoring:
  enabled: false
registries:
  configs:
    rgcrprod.azurecr.us:
      authConfigSecretName: carbide-registry
      caBundle: ''
      insecureSkipVerify: false
rke:
  localClusterAuthEndpoint:
    enabled: false
nodepools:
- etcd: true
  controlplane: true
  worker: false
  displayName: control-plane-a
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  name: control-plane-hiperf-tyreek-pool-a
  ami: ami-0a695f0d95cefc163
  deviceName: /dev/sda1
  encryptEbsVolume: false
  endpoint: ""
  iamInstanceProfile: RancherIAMCloudProvider
  insecureTransport: false
  instanceType: t3a.xlarge
  region: us-east-2
  createSecurityGroup: true
  securityGroups: []
  keypairName: ""
  securityGroupReadonly: false
  sshKeyContents: ""
  subnetId: subnet-0d8416be857cba803
  monitoring: false
  openPort:
  - "8080"
  - "8443"
  - "443"
  privateAddressOnly: false
  requestSpotInstance: false
  tags: Owner,brian,KeepRunning,true
  retries: 5
  rootSize: 60
  sshUser: ubuntu
  volumeType: gp2
  vpcId: vpc-06cec89a153c4d640
  useEbsOptimizedInstance: false
  usePrivateAddress: false
  userdata: |
    #cloud-config
    runcmd:
    - curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
    - curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
    - apt update
    - apt install -y tailscale
    - systemctl enable --now tailscaled
    - tailscale up --authkey= --accept-routes
  zone: a
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-a
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  name: worker-hiperf-tyreek-pool-a
  ami: ami-0a695f0d95cefc163
  deviceName: /dev/sda1
  encryptEbsVolume: false
  endpoint: ""
  iamInstanceProfile: RancherIAMCloudProvider
  insecureTransport: false
  instanceType: g4dn.2xlarge
  region: us-east-2
  createSecurityGroup: true
  securityGroups: []
  keypairName: ""
  securityGroupReadonly: false
  sshKeyContents: ""
  subnetId: subnet-0d8416be857cba803
  monitoring: false
  openPort:
  - "8080"
  - "8443"
  - "443"
  privateAddressOnly: false
  requestSpotInstance: false
  tags: owner,brian,KeepRunning,true
  retries: 5
  rootSize: 120
  sshUser: ubuntu
  volumeType: gp2
  vpcId: vpc-06cec89a153c4d640
  useEbsOptimizedInstance: false
  usePrivateAddress: false
  userdata: |
    #cloud-config
    package_update: true
    packages:
    - nvidia-driver-520
    runcmd:
    runcmd:
    - curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
    - curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
    - apt update
    - apt install -y tailscale
    - systemctl enable --now tailscaled
    - tailscale up --authkey= --accept-routes
    - reboot
  zone: a
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-b
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  name: worker-hiperf-tyreek-pool-b
  ami: ami-0a695f0d95cefc163
  deviceName: /dev/sda1
  encryptEbsVolume: false
  endpoint: ""
  iamInstanceProfile: RancherIAMCloudProvider
  insecureTransport: false
  instanceType: g4dn.2xlarge
  region: us-east-2
  createSecurityGroup: true
  securityGroups: []
  keypairName: ""
  securityGroupReadonly: false
  sshKeyContents: ""
  subnetId: subnet-05568bc187634e4b0
  monitoring: false
  openPort:
  - "8080"
  - "8443"
  - "443"
  privateAddressOnly: false
  requestSpotInstance: false
  tags: owner,brian,KeepRunning,true
  retries: 5
  rootSize: 120
  sshUser: ubuntu
  volumeType: gp2
  vpcId: vpc-06cec89a153c4d640
  useEbsOptimizedInstance: false
  usePrivateAddress: false
  userdata: |
    #cloud-config
    package_update: true
    packages:
    - nvidia-driver-520
    runcmd:
    runcmd:
    - curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
    - curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
    - apt update
    - apt install -y tailscale
    - systemctl enable --now tailscaled
    - tailscale up --authkey= --accept-routes
    - reboot
  zone: b
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-c
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  name: worker-hiperf-tyreek-pool-c
  ami: ami-0a695f0d95cefc163
  deviceName: /dev/sda1
  encryptEbsVolume: false
  endpoint: ""
  iamInstanceProfile: RancherIAMCloudProvider
  insecureTransport: false
  instanceType: g4dn.2xlarge
  region: us-east-2
  createSecurityGroup: true
  securityGroups: []
  keypairName: ""
  securityGroupReadonly: false
  sshKeyContents: ""
  subnetId: subnet-0a2bf7fcf6009f864
  monitoring: false
  openPort:
  - "8080"
  - "8443"
  - "443"
  privateAddressOnly: false
  requestSpotInstance: false
  tags: owner,brian,KeepRunning,true
  retries: 5
  rootSize: 120
  sshUser: ubuntu
  volumeType: gp2
  vpcId: vpc-06cec89a153c4d640
  useEbsOptimizedInstance: false
  usePrivateAddress: false
  userdata: |
    #cloud-config
    package_update: true
    packages:
    - nvidia-driver-520
    runcmd:
    runcmd:
    - curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
    - curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
    - apt update
    - apt install -y tailscale
    - systemctl enable --now tailscaled
    - tailscale up --authkey= --accept-routes
    - reboot
  zone: c
