cloudprovider: harvester
cloudCredentialSecretName: cattle-global-data:deathstar
cloudProviderConfigSecretName: secret://fleet-default:devfluffymunchkin-cloudprovider
cluster:
  annotations: {}
  labels:
    environment: dev
    cluster_name: fluffymunchkin
    location: deathstar
  name: dev-fluffymunchkin
kubernetesVersion: v1.24.7+k3s1
registries:
  configs:
    rgcrprod.azurecr.us:
      authConfigSecretName: carbide-registry
      caBundle: ''
      insecureSkipVerify: false
  mirrors:
    docker.io:
      endpoint:
        - harbor.sienarfleet.systems
monitoring:
  enabled: false
rke:
  localClusterAuthEndpoint:
    enabled: false
nodepools:
- etcd: true
  controlplane: true
  worker: true
  displayName: control-plane-nodes
  name: control-plane-dev-pool
  labels: {}
  taints: {}
  quantity: 1
  paused: false
  diskSize: 20
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/dev
  networkType: dhcp
  imageName: default/ubuntu-rke2-airgap-harvester
  vmNamespace: default
  sshUser: ubuntu
  userdata: ""
- etcd: false
  controlplane: false
  worker: true
  displayName: worker-nodes
  name: worker-dev-pool
  labels: {}
  taints: {}
  quantity: 3
  paused: false
  diskSize: 40
  diskBus: virtio
  cpuCount: 2
  memorySize: 4
  networkName: default/dev
  networkType: dhcp
  imageName: default/ubuntu-rke2-airgap-harvester
  vmNamespace: default
  sshUser: ubuntu
  userdata: ""
