externalURL: https://harbor.svc.mustafar.lol

harborAdminPassword: "Harbor12345"

updateStrategy:
  type: Recreate

expose:
  ingress:
    hosts:
      core: harbor.svc.mustafar.lol
      notary: notary.svc.mustafar.lol

persistence:
  persistentVolumeClaim:
    registry:
      size: 5Gi
      storageClass: "longhorn"
    chartmuseum:
      storageClass: "longhorn"
    jobservice:
      storageClass: "longhorn"
    database:
      storageClass: "longhorn"
    redis:
      storageClass: "longhorn"
    trivy:
      storageClass: "longhorn"
portal:
  image:
    repository: harbor.mustafar.lol/goharbor/harbor-portal
    tag: v2.5.3
core:
  image:
    repository: harbor.mustafar.lol/goharbor/harbor-core
    tag: v2.5.3
jobservice:
  image:
    repository: harbor.mustafar.lol/goharbor/harbor-jobservice
    tag: v2.5.3
registry:
  registry:
    image:
      repository: harbor.mustafar.lol/goharbor/registry-photon
      tag: v2.5.3
  controller:
    image:
      repository: harbor.mustafar.lol/goharbor/harbor-registryctl
      tag: v2.5.3
chartmuseum:
  image:
    repository: harbor.mustafar.lol/goharbor/chartmuseum-photon
    tag: v2.5.3
trivy:
  image:
    repository: harbor.mustafar.lol/goharbor/trivy-adapter-photon
    tag: v2.5.3
notary:
  server:
    image:
      repository: harbor.mustafar.lol/goharbor/notary-server-photon
      tag: v2.5.3
  signer:
    image:
      repository: harbor.mustafar.lol/goharbor/notary-signer-photon
      tag: v2.5.3
database:
  internal:
    image:
      repository: harbor.mustafar.lol/goharbor/harbor-db
      tag: v2.5.3
redis:
  internal:
    image:
      repository: harbor.mustafar.lol/goharbor/redis-photon
      tag: v2.5.3

