kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: compliance
  namespace: fleet-default
spec:
  repo: https://github.com/bcdurden/deathstar_builder.git
  branch: main

  # To target specific clusters, uncomment this block
  targets:
  - clusterSelector:
      matchLabels:
        environment: services
  - clusterSelector:
      matchLabels:
        environment: prod
  - clusterSelector:
      matchLabels:
        location: homelab

  paths:
  - "./gitops/apps/compliance"